CREATE TABLESPACE tbs_LOG_AUDIT DATAFILE
    SIZE 10 M
        AUTOEXTEND ON MAXSIZE UNLIMITED;

CREATE USER LOG_AUDIT IDENTIFIED BY LOG_AUDIT123
    DEFAULT TABLESPACE tbs_LOG_AUDIT
    QUOTA UNLIMITED ON tbs_LOG_AUDIT;

GRANT CREATE SESSION TO log_audit;