CREATE  TABLESPACE tbs_LOG_AUDIT
  DATAFILE 'tbs_LOG_AUDIT.dat'
  SIZE 10M AUTOEXTEND ON  MAXSIZE UNLIMITED;
/

CREATE USER LOG_AUDIT IDENTIFIED BY LOG_AUDIT
    DEFAULT TABLESPACE tbs_LOG_AUDIT
    QUOTA UNLIMITED ON tbs_LOG_AUDIT;
--/
--GRANT CREATE SESSION TO log_audit;