CREATE SEQUENCE log_audit.seq_increment
 START WITH     1
 INCREMENT BY   1
 MINVALUE 1
 MAXVALUE 50
 CACHE 20
 CYCLE;
/
CREATE SEQUENCE log_audit.seq_CONTEXT
 START WITH     1
 INCREMENT BY   1
 MINVALUE 1
 CACHE 20
 NOCYCLE;
